name: eqdashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.19.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dmdata_api:
    path: ../packages/dmdata_api
  dmdata_oauth_flutter:
    path: ../packages/dmdata_oauth_flutter
  flutter:
    sdk: flutter
  flutter_appauth: ^8.0.3
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  hooks_riverpod: ^2.6.1
  intl: ^0.20.1
  json_annotation: ^4.9.0
  macos_ui: ^2.0.9
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.3
  synchronized: ^3.3.0+3
  url_launcher: ^6.3.1

dev_dependencies:
  altive_lints: ^1.16.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  eqdashboard_lints:
    path: ../packages/eqdashboard_lints
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
