name: eqdashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

dependencies:
  collection: ^1.19.0
  cupertino_icons: ^1.0.8
  cupertino_sidebar: ^1.0.1
  dio: ^5.7.0
  dmdata_api:
    path: ../packages/dmdata_api
  dmdata_oauth_flutter:
    path: ../packages/dmdata_oauth_flutter
  flutter:
    sdk: flutter
  flutter_appauth: ^8.0.3
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^9.2.2
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  hooks_riverpod: ^2.6.1
  intl: ^0.20.1
  json_annotation: ^4.9.0
  macos_ui: ^2.0.9
  ntp: ^2.0.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.3
  synchronized: ^3.3.0+3
  talker: ^4.5.2
  talker_dio_logger: ^4.5.2
  talker_flutter: ^4.5.2
  talker_logger: ^4.5.2
  talker_riverpod_logger: ^4.5.2
  url_launcher: ^6.3.1

dev_dependencies:
  altive_lints: ^1.16.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  eqdashboard_lints:
    path: ../packages/eqdashboard_lints
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 900
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-ExtraBold.ttf
          weight: 900

flutter_gen:
  output: lib/core/gen/
  line_length: 80
