name: eqdashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  app_links: ^6.3.3
  dmdata_oauth_flutter:
    path: ../packages/dmdata_oauth_flutter
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.4
  flutter_appauth: ^8.0.3
  flutter_hooks: ^0.20.5
  flutter_secure_storage: ^4.2.1
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.3

dev_dependencies:
  altive_lints: ^1.16.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  yumemi_lints: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
