targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true
          field_rename: snake
      freezed:
        generate_for:
          include:
            - lib/src/model/**.dart
