name: dmdata_oauth_flutter
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  flutter_secure_storage: ^4.2.1
  json_annotation: ^4.9.0
  dmdata_oauth_api_client:
    path: ../dmdata_oauth_api_client

dev_dependencies:
  build_runner: ^2.4.13
  eqdashboard_lints:
    path: ../eqdashboard_lints
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  custom_lint: ^0.7.0
  mocktail: ^1.0.0
  flutter_test:
    sdk: flutter
