name: "Setup Application Runtime"
description: "Setup application runtime for Flutter"

runs:
  using: "composite"
  steps:
    # https://github.com/kuhnroyal/flutter-fvm-config-action
    - name: Fetch flutter config
      uses: kuhnroyal/flutter-fvm-config-action@60c14af316b09f8819202d845391260cf3b979c9 # v3.0
      id: fvm-config-action

    # https://github.com/subosito/flutter-action
    - name: Setup flutter
      uses: subosito/flutter-action@f2c4f6686ca8e8d6e6d0f28410eeef506ed66aff # v2.18.0
      with:
        flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
        cache: true

    # https://github.com/actions/cache
    - name: Cache pubspec dependencies
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: |
          ~/.pub-cache
        key: pubspec-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          pubspec-

    - name: Setup melos
      run: |
        mkdir -p .fvm
        ln -s $FLUTTER_ROOT .fvm/flutter_sdk
        MELOS_VERSION=$(cat pubspec.lock | yq ".packages.melos.version" -r)
        dart pub global activate melos $MELOS_VERSION
      shell: bash

    - name: Resolve dependencies
      shell: bash
      run: melos bootstrap
